
# Parse csv generated by minnoJS
#
# @param df a data frame
# @param id the column name holding the ids
# @param data the column name holding the data (we assume the data holds an array of unnested objects)
#
# @example
# minno.parse.quoted(df, 'id', 'Q_47')
# minno.parse(df, id, Q_47)
#
# @returns data frame with parsed data, rows with NA or '' are omitted.

minno.parse.quoted = function(df, id, data){
  filteredDF = df[df[,data]!='' & !is.na(df[,data]) ,]
  
  # parse data -> list of data data frames
  csvList = lapply(filteredDF[,data], function(str) tryCatch({
    read.csv(text=str,stringsAsFactors = FALSE)
  },
  error = function(err){
    message('woa there is a malformed csv here')
    return(NA)
  }
  ))
  
  # add id to each data DF
  mask = which(sapply(csvList,nrow)>0)
  dataPages = mapply(
    function(id, df) cbind(id,df),
    filteredDF[mask,id],
    csvList[mask],
    SIMPLIFY = FALSE
  )
  
  if (!length(dataPages)) { return(data.frame()) }
  
  # concat pages
  do.call(rbind,dataPages)
}

minno.parse = function(df, id, data){
  minno.parse.quoted(df, deparse(substitute(id)), deparse(substitute(data)))
}

# for testing:
df = data.frame(id = c(1,2,3,6,5), Q_47= c('',NA,'first,second\nthird,fourth\n5,6','first,second\n1,2','first,second\nthird,fourth\n'))
minno.parse(df, id, Q_47)