library(jsonlite)

# Parse json generated by minnoJS
#
# @param df a data frame
# @param id the column name holding the ids
# @param json the column name holding the json (we assume the json holds an array of unnested objects)
#
# @example
# minno.parse.quoted(df, 'id", 'Q_47')
# minno.parse(df, id, Q_47)
#
# @returns data frame with parsed json, rows with NA or '' are omitted.

minno.parse.quoted = function(df, id, json){
  # filter empty json rows
  filteredDF = df[df[,json]!='' & !is.na(df[,json]) ,]
  # json to char
  jsonStrings = sapply(filteredDF[,json], as.character)
  # parse json -> list of json data frames
  jsonDF = lapply(jsonStrings, fromJSON)
  # add id to each json DF
  jsonPages = mapply(function(id, df) cbind(id,df), filteredDF[,id], jsonDF, SIMPLIFY = FALSE)
  # concat pages
  rbind_pages(jsonPages)
}

minno.parse = function(df, id, json){
  minno.parse.quoted(df, deparse(substitute(id)), deparse(substitute(json)))
}

# for testing:
#df = data.frame(id = c(1,2,3,4,5), Q_47= c('[{"a":1,"b":2},{"a":3,"b":4}]','',NA,'[{"a":5,"b":6},{"a":7,"b":8}]','[{"a":9,"b":10},{"a":11,"b":12}]'))
#minno.parse(df, id, Q_47)